services:
  api:
    build: .
    volumes:
      - .:/backend
    ports:
      - "8001:8000"
    depends_on:
      - db
    env_file:
      - .env.dev
    restart: always

  db:
    image: postgres:17
    volumes:
      - sca_data:/var/lib/postgresql/data
    env_file:
      - .env.dev
    restart: always

volumes:
  sca_data:

